edition = "2024"
max_width = 100
use_small_heuristics = "Max"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true

remove_nested_parens = true
combine_control_expr = true