[package]
name = "preprocessor"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
common = { path = "../../crates/common" }
codec = { path = "../../crates/codec" }
anyhow = "1.0.100"
rayon = "1.11.0"
log = "0.4.28"
