[package]
name = "network"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
once_cell = "1.21.3"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
anyhow = "1.0.100"
protocol = { path = "../protocol"}
postcard = { version = "1.1.3", features = ["alloc"] }
